############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Team"
url = "team/"
weight = 2

[[main]]
name = "Service"
url = "service/"
weight = 3

[[main]]
name = "Articles"
url = "blog/"
weight = 4

[[main]]
name = "FAQ"
url = "faq/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Team"
url = "team/"
weight = 1

[[footer]]
name = "Service"
url = "service/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3

[[footer]]
name = "FAQ"
url = "faq/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5